src/Entity/Course.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CourseRepository")
 */
class Course
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $points;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual("today")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual("today")
     */
    private $end_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CourseUser", mappedBy="course")
     */
    private $courseUser;

    public function __construct()
    {
        $this->courseUser = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPoints(): ?int
    {
        return $this->points;
    }

    public function setPoints(?int $points): self
    {
        $this->points = $points;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection|CourseUser[]
     */
    public function getCourseUser(): Collection
    {
        return $this->courseUser;
    }

    public function addCourseUser(CourseUser $courseUser): self
    {
        if (!$this->courseUser->contains($courseUser)) {
            $this->courseUser[] = $courseUser;
            $courseUser->setCourse($this);
        }

        return $this;
    }

    public function removeCourseUser(CourseUser $courseUser): self
    {
        if ($this->courseUser->contains($courseUser)) {
            $this->courseUser->removeElement($courseUser);
            // set the owning side to null (unless already changed)
            if ($courseUser->getCourse() === $this) {
                $courseUser->setCourse(null);
            }
        }

        return $this;
    }
}

src/Form/CourseType.php
<?php

namespace App\Form;

use App\Entity\Course;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('points')
            ->add('start_date', DateType::class,[
                'widget' => 'single_text',
            ])
            ->add('end_date', DateType::class,[
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Course::class,
        ]);
    }
}

src/Controller/CourseController.php
<?php

namespace App\Controller;

use App\Entity\Course;
use App\Entity\CourseUser;
use App\Form\CourseType;
use App\Repository\CourseRepository;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function MongoDB\BSON\toJSON;

/**
 * @Route("/course")
 */
class CourseController extends AbstractController
{
    /**
     * @Route("/", name="course_index", methods={"GET"})
     */
    public function index(CourseRepository $courseRepository): Response
    {
        return $this->render('course/index.html.twig', [
            'courses' => $courseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="course_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $course = new Course();
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($course);
            $entityManager->flush();

            return $this->redirectToRoute('course_index');
        }

        return $this->render('course/new.html.twig', [
            'course' => $course,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="course_show", methods={"GET"})
     */
    public function show(Course $course): Response
    {
        $averageGrade = $this->getDoctrine()
            ->getRepository(CourseUser::class)
            ->getAverageGradeOnCourse($course->getId());

        // get grades
        $grades = $this->getDoctrine()
            ->getRepository(CourseUser::class)
            ->getGrades($course->getId());

        // manipulate data - convert array data[1] should be int not string for graph
        $test = [];
        foreach ($grades as $grade){
            $grade['count'] = (int) $grade['count'];
            array_push($test, $grade);
//            $test['points'] = $grade['points'];
//            $test['count'] = $grade['count'];
        }

        // add first row for pie chart
        array_unshift($test, ['Col1','Col2']);

        $pieChart = new PieChart();
        $pieChart->getData()->setArrayToDataTable(
            $test
        );

        $pieChart->getOptions()->setTitle('My Daily Activities');
        $pieChart->getOptions()->setHeight(500);
        $pieChart->getOptions()->setWidth(900);
        $pieChart->getOptions()->getTitleTextStyle()->setBold(true);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#009900');
        $pieChart->getOptions()->getTitleTextStyle()->setItalic(true);
        $pieChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(20);

        return $this->render('course/show.html.twig', [
            'course' => $course,
            'averageGrade' => $averageGrade,
            'grades' => $grades,
            'piechart' => $pieChart
        ]);
    }

    /**
     * @Route("/{id}/edit", name="course_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Course $course): Response
    {
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('course_index');
        }

        return $this->render('course/edit.html.twig', [
            'course' => $course,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="course_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Course $course): Response
    {
        if ($this->isCsrfTokenValid('delete' . $course->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($course);
            $entityManager->flush();
        }

        return $this->redirectToRoute('course_index');
    }
}

templates/course/_delete_form.html.twig
<form method="post" action="{{ path('course_delete', {'id': course.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ course.id) }}">
    <button class="btn btn-danger float-left">Delete</button>
</form>

templates/course/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-success float-left  mr-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/course/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Course{% endblock %}

{% block body %}
    <h1>Edit Course</h1>

    <div class="clearfix">
        {{ include('course/_form.html.twig', {'button_label': 'Update'}) }}
        {{ include('course/_delete_form.html.twig') }}
    </div>
    <a href="{{ path('course_index') }}">Back to list</a>

{% endblock %}

templates/course/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Course index{% endblock %}

{% block body %}
    <h1>Course index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Points</th>
            <th>Start_date</th>
            <th>End_date</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for course in courses %}
            <tr>
                <td>{{ course.id }}</td>
                <td>{{ course.name }}</td>
                <td>{{ course.description }}</td>
                <td>{{ course.points }}</td>
                <td>{{ course.startDate ? course.startDate|date('Y-m-d') : '' }}</td>
                <td>{{ course.endDate ? course.endDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('course_show', {'id': course.id}) }}" class="btn btn-info">Show</a>
                    <a href="{{ path('course_edit', {'id': course.id}) }}" class="btn btn-success">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('course_new') }}">Create new</a>
{% endblock %}

templates/course/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Course{% endblock %}

{% block body %}
    <h1>Create new Course</h1>

    {{ include('course/_form.html.twig') }}
    <div class="clearfix"></div>
    <a href="{{ path('course_index') }}">Back to list</a>
{% endblock %}

templates/course/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Course{% endblock %}

{% block body %}
    <h1>Course</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ course.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ course.name }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ course.description }}</td>
        </tr>
        <tr>
            <th>Points</th>
            <td>{{ course.points }}</td>
        </tr>
        <tr>
            <th>Start_date</th>
            <td>{{ course.startDate ? course.startDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>End_date</th>
            <td>{{ course.endDate ? course.endDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Average grade</th>
            <td>{{ averageGrade[1] }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('course_edit', {'id': course.id}) }}" class="btn btn-success float-left mr-2">Edit</a>

    {{ include('course/_delete_form.html.twig') }}

    <div class="clearfix"></div>
    <a href="{{ path('course_index') }}">Back to list</a>

    <div id="div_chart"></div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        {{ gc_draw(piechart, 'div_chart') }}
    </script>

{% endblock %}